# Generated by Django 5.2.7 on 2025-10-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Store normalized phone (E.164) if possible, e.g. +9617XXXXXXX', max_length=32, null=True)),
                ('instagram_account', models.CharField(blank=True, help_text='Instagram handle or business id (e.g. @shopname)', max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_lbp', models.BigIntegerField(blank=True, help_text='Store as integer LBP', null=True)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'sku'], name='core_produc_busines_5bd59b_idx'), models.Index(fields=['business', 'name'], name='core_produc_busines_8901ea_idx')],
            },
        ),
    ]
