# Generated by Django 5.2.7 on 2025-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instagram_integration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='core_custom_busines_696f03_idx',
            old_name='core_customer_business_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='core_custom_platfor_ac90a9_idx',
            old_name='core_customer_platform_id_idx',
        ),
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='core_messag_busines_a00393_idx',
            old_name='core_messagelog_business_created_idx',
        ),
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='core_messag_custome_02332d_idx',
            old_name='core_messagelog_customer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='core_messag_directi_9c1add_idx',
            old_name='core_messagelog_direction_created_idx',
        ),
    ]
