# Generated by Django 5.2.7 on 2025-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_and_product_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Owner toggle for AI auto-replies'),
        ),
        migrations.AddField(
            model_name='business',
            name='allow_auto_reply_from_unknown',
            field=models.BooleanField(default=False, help_text='Whether to auto-reply to first-time senders'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID linked to the Instagram Business account', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='page_access_token',
            field=models.TextField(blank=True, help_text='Page Access Token for sending messages via Instagram API', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='page_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry timestamp for the page access token', null=True),
        ),
    ]
