# Generated by Django 5.2.7 on 2025-10-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global category. If set, this is business-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.business'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Global categories are available to all businesses'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'business': models.F('business')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'business')},
        ),
    ]
