# Generated by Django 5.2.7 on 2025-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_business_category_is_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='URL of the product image stored in Supabase', max_length=500, null=True),
        ),
    ]
