# Generated by Django 5.2.7 on 2025-10-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('embedding', models.TextField(help_text='Vector embedding as JSON string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'db_table': 'product_embeddings',
            },
        ),
        migrations.CreateModel(
            name='MediaToProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(help_text='Instagram media ID or custom identifier', max_length=255)),
                ('confidence', models.FloatField(help_text='Similarity score (0.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_mappings', to='core.product')),
            ],
            options={
                'verbose_name': 'Media to Product Mapping',
                'verbose_name_plural': 'Media to Product Mappings',
                'db_table': 'media_to_product_map',
                'unique_together': {('media_id', 'business')},
            },
        ),
    ]
